default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin 
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  database: postgres

production:
  <<: *default
  database: postgres