default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: development.sqlite3

production:
  <<: *default
  database: postgres