development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: swifttask
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: swifttask
  password: admin